### ISSUE TITLE
修改了源码，让其不再依赖zepto／jquery

### ISSUE THREAD

**Issue by bigmeow** [gtdalp/listloading#13]
地址：https://github.com/bigmeow/listloading
可以在readme.md里链一下，作者可以帮忙检查下是否完全移除了依赖

**Comment by gtdalp** [comment]
可以呀 我一直想做这个 想不到不抢先了一步 niubility

**Comment by bigmeow** [comment]
@gtdalp 测试了下  发现关于事件那一块还没弄  你来？

**Comment by gtdalp** [comment]
@bigmeow 大兄弟 你有空可以帮弄一下咯，我一直没有空去整。。。工作太忙了 ths
