### ISSUE TITLE
为什么我还没开始刷新，一进来会这样显示？

### ISSUE THREAD

**Issue by NGyc** [gtdalp/listloading#15]
![_20171011093057](https://user-images.githubusercontent.com/23099333/31418263-a9a6f704-ae67-11e7-8f2c-4e65defb5aa7.png)

**Comment by gtdalp** [comment]
你看看滚动内容父元素设定有高度没有

**Comment by NGyc** [comment]
有设定的

**Comment by gtdalp** [comment]
发一个demo过来 我看看

**Comment by gtdalp** [comment]
目测你这个图片，好像就是没有在初始化的时候设定父元素的高度导致的问题，你参照一下demo来写试试
