### ISSUE TITLE
nam引入listloading组件使用是js报错

### ISSUE THREAD

**Issue by baoman** [gtdalp/listloading#2]
nam install listloading -S后拷贝示例代码后报下面的错
listloading.js:402 Uncaught ReferenceError: IScroll is not defined(…)

难道此组件不适用npm引入吗

**Comment by baoman** [comment]
self.iscroll = new IScroll('#' + self.id, obj);这行代码报错

**Comment by gtdalp** [comment]
nam？？？是写错了吗？应该是npm吧，listloading是需要依赖iscroll.js，你需要引入iscroll.js文件.

**Comment by baoman** [comment]
不好意思 是我打错了字 组件是已经下载下来了的  组件不应该把依赖写好吗 用的时候应该就不要额外引入文件了

**Comment by baoman** [comment]
我在list loading.js里面第一行加入“var IScroll = require("../src/jslib/iscroll.min");”就可以直接用npm方式  不需要额外再引入iScroll.js了 你是否需要改进下 因为模块好的方式是自己解决依赖 不要使用的时候加入依赖

**Comment by gtdalp** [comment]
既然使用了listloading，那么是必须要依赖iscroll的，如果你想要创建iscroll的话也可以直接使用listloading来创建iscroll，
如：
```javascript
new Listloading('#listloading');  
```
或者
```javascript
new Listloading('#listloading',{
       // iscroll的API 
       iscrollOptions: {
            // scrollbars: true   // 显示iscroll滚动条
        }
});
```

**Comment by microlv** [comment]
so you are copy iscroll to your folder jslib and iscroll can't update any more.
that seems a bad idea.

**Comment by gtdalp** [comment]
Sorry，I will be optimized！ @microlv
