### ISSUE TITLE
如果 自动加载的数据不满屏幕高度的时候，应该要自动加载下一页，直到数据为空或者，超出屏幕视窗高度～

### ISSUE THREAD

**Issue by Sapphire2k** [gtdalp/listloading#4]
现在的情况就是，如果屏幕高度是需要15条数据才能铺满的话，局限于后端接口返回的数据 每次只有十条，那么上拉的样式是不会加载的，需要手动加载下一页或者更改每次返回的数据长度

**Comment by gtdalp** [comment]
是的，容器里面必须是要超过一屏 才会出现上拉加载更多。

**Comment by Sapphire2k** [comment]
@gtdalp 这样的话，体验不会是特别好，得手动加载一页。我用了蛮多插件，都是如果未满一屏，可以尝试自动加载第二页，直到超过一屏，不然就没法下拉了，即使后面还有数据～可以考虑在option里加一个字段～

**Comment by gtdalp** [comment]
设计组件当初我已经想到这个问题，我统计过，基本有上拉刷新的情况内容都会超过一屏，如果不超过，UI设计还是很小气那种，这个我建议你可以去与设计商量，重新设计一下。
