### ISSUE TITLE
可不可以实现点击进入详情页，返回还在原来位置

### ISSUE THREAD

**Issue by TuKun33** [gtdalp/listloading#6]
这在微信浏览器返回里会刷新页面

**Comment by gtdalp** [comment]
多页面，js是控制不了返回键的。

**Comment by gtdalp** [comment]
js无法控制返回键，返回页面刷新是浏览器自带的，所以组件也控制不了返回原来位置，如果是单页面应用可以实现。

**Comment by TuKun33** [comment]
没办法啊，有这个需求，不然体验很差

**Comment by gtdalp** [comment]
前端是无法控制浏览器的返回按键，返回到之前的页面自己刷新也是浏览器自己控制的啊！前端都应该懂这个原理咯！
