### ISSUE TITLE
同个页面多个下拉刷新有问题

### ISSUE THREAD

**Issue by suyana** [gtdalp/listloading#7]
也不知道是不是我写法问题，如果一个页面有tab，每个tab都要做下拉、上拉功能，我这边新建了多个实例，但是结果是除了第一个一开始显示的tab外，其他tab一直显示下拉刷新那个框框，且无法拖动

**Comment by gtdalp** [comment]
我刚添加了一个demo，在根目录tabdemo下面，你可以下载参照一下。

**Comment by suyana** [comment]
非常感谢，作者好快，真的非常感谢
